### ISSUE TITLE
Change default mpl histogram legend marker

### ISSUE THREAD

**Issue by aperloff** [scikit-hep/mplhep#21]
The default legend marker style for an Matplotlib histogram (i.e. ax.hist()) is a filled box, even if the histogram is a colored line with no fill. The CMS style is to use a colored lined in this instance. The way I handled this was:
```python
handles, labels = ax.get_legend_handles_labels()
new_handles = [Line2D([], [], c=h.get_edgecolor()) if type(h)==mpl.patches.Polygon else h for h in handles]
legend = ax.legend(handles=new_handles[::-1], labels=labels[::-1], loc='upper right', fontsize=18)
```
It would be nice if mplhep would handle this automatically.

**Comment by andrzejnovak** [comment]
Oh, to be clear, you are talking about `pyplot.hist` not `mplhep.histplot` ?

**Comment by aperloff** [comment]
Yes. Is it still possible to format the legend correctly when using the cms style?

**Comment by andrzejnovak** [comment]
Not really, the cms style is just a dictionary with the matplotlib configs (not all things are configurable). Though your snippet could be put into some kinds of `cms_magic()` function that would align ax labels, fix legends or adjust limits as I guess is the topic of #22 . Though I would be wary of the limit adjustment because if it happens in a non-obvious way, people might ask more questions about where their data went.

**Comment by aperloff** [comment]
Maybe just a helper function to CMS-ify the legend? You can put this in to start and then add to it later if others have legend specific style requirements for CMS.
