### ISSUE TITLE
Hardcoded error defaults shadows rc settings

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/mplhep#225]
The defaults of an error plot are hardcoded inside the function:
https://github.com/scikit-hep/mplhep/blob/286639cf9bcf98cf26e8be55461ce616649ca8c7/src/mplhep/plot.py#L382

This renders style setting useless for this plot. Can we somehow pass them through, define them as well in the style settings? Or just not use the defaults? Currently, a style cannot change this.

**Comment by andrzejnovak** [comment]
Some defaults are needed, otherwise a plot that should look like this without any applied style
![image](https://user-images.githubusercontent.com/13226500/98830926-3ec99200-243b-11eb-99dc-ad2e08694b6b.png)
ends up looking like this
![image](https://user-images.githubusercontent.com/13226500/98830893-35402a00-243b-11eb-9ea1-c88864ff2649.png)

We could probably extend the checking to see if any rcParams are modified from the mpl baseline and if so, don't overwrite them

**Comment by mayou36** [comment]
Yes, I fully agree on the defaults to be there. Maybe we can also just add "other fields" to the rc parameters? Basically defaults for mplhep and not for matplotlib which are though in the same style dict?

But that's maybe a second order problem, I agree to go with checking the style dict first.

What is problematic about this: that the markers etc are often with a lineplot in mind, not with an errorbar plot. So these seem two different things actually.

**Comment by andrzejnovak** [comment]
> Yes, I fully agree on the defaults to be there. Maybe we can also just add "other fields" to the rc parameters? Basically defaults for mplhep and not for matplotlib which are though in the same style dict?

This would alter the API, because you could no longer pass the dict directly to `plt.style.use`


> What is problematic about this: that the markers etc are often with a lineplot in mind, not with an errorbar plot. So these seem two different things actually.

Are any of the current defaults in conflict because of that? I don't think so and anyway this would have to be solved in mpl.

**Comment by andrzejnovak** [comment]
This is fixed https://github.com/scikit-hep/mplhep/blob/master/src/mplhep/plot.py#L401
