### ISSUE TITLE
feat: we should be able to combine years, lumis, and coms together

### ISSUE THREAD

**Issue by ikrommyd** [scikit-hep/mplhep#456]
Very often in plots, we combine different data taking periods together. Therefore we should be able to specify lists of lumis, years and coms of the same length together and mplhep should create a label like the following image:
<img width="568" alt="image" src="https://github.com/scikit-hep/mplhep/assets/82155404/cbdce313-4bd4-444e-9ab4-8d1101fb8c1e">

If that's already there and I'm not seeing it I'm sorry.

**Comment by andrzejnovak** [comment]
This already exists in the form of `rlabel=` which forces whatever text you want on the right side. The label you posted is imo too specific to generate it programmatically from some lists.

**Comment by andrzejnovak** [comment]
I don't personally think this is particularly simpler for the user in the sense that what if they prefer to write eg `92fb (13; 13,6 TeV) 2018-2022` instead. Feel free to correct me if we have a definite guidance on how this should be structured (at least in CMS). That said, since your proposal doesn't really change the API and the logic should be pretty straightforward for future maintenance, I am ok to merge it if you want to submit a PR.

Side note since this label would likely be too long to have the CMS label also on top, ideally this could come with new functionality that check for overlap and emit a warning for the user to use the in-frame CMS label position.

**Comment by iasonkrom** [comment]
Yeah you can use this `92fb (13; 13,6 TeV) 2018-2022` if it is somewhat a continuous data taking period. I think the format I typed is the standard according to guidelines (at least in CMS) when we refer to different discreet years. I just got this idea because I'm currently preparing the DPS note presentation for E/Gamma and I wanted to use this format. I'm very busy these days but I will read more to see if there is some generic guideline (also for other experiments) and create a simple PR to do this. You can close this issue if you want in the meantime if you don't want issue cluttering.
